default_language_version:
  python: python3

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-merge-conflict
      - id: check-added-large-files
      - id: check-docstring-first
      - id: check-json
        exclude: ^(.devcontainer/.*\.json)$
      - id: check-xml
      - id: trailing-whitespace
      - id: end-of-file-fixer
        exclude: \.txt$
      - id: no-commit-to-branch
        args: [--branch, main]


  # To remove useless imports
  - repo: https://github.com/PyCQA/autoflake
    rev: v2.3.1
    hooks:
    -   id: autoflake
        args: [--remove-all-unused-imports, --remove-unused-variables, --ignore-init-module-imports, --in-place, --recursive]
  # To sort imports alphabetically and automatically separate them into sections
  - repo: https://github.com/facebook/usort
    rev: v1.0.7
    hooks:
      - id: usort

  # To format Python code
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
