DISABLE_LLM_CONNECTION = False

AZURE_API_KEY_PATH = 'azure_api_key.txt'
AZURE_ENDPOINT = 'azure_endpoint.txt'
AZURE_OPENAI_MODEL = 'azure_openai_model.txt'
DEFAULT_API_URL = "http://dgx.fit.fraunhofer.de"
DEFAULT_LLM = "llama3.3:70b"
DEFAULT_CONTEXT_SIZE = 1024 * 64

# can be either 'json', 'xml', 'simplified_xml' (the entire process model is provided for xml and simplified xml), or 'svg' (a picture of the process model is uploaded)
MODEL_ABSTRACTION = "simplified_xml"

DEFAULT_ENABLE_PROMPT_STRATEGIES = True
ENABLE_ROLE_PROMPTING = DEFAULT_ENABLE_PROMPT_STRATEGIES
ENABLE_KNOWLEDGE_INJECTION = False
ENABLE_NATURAL_LANGUAGE_RESTRICTION = DEFAULT_ENABLE_PROMPT_STRATEGIES
ENABLE_CHAIN_OF_THOUGHT = False
ENABLE_PROCESS_ANALYSIS = False
ENABLE_FEW_SHOTS_LEARNING = False
ENABLE_NEGATIVE_PROMPTING = False
ENABLE_EXAMPLES = True
COMPANY_CONTEXT = True

MAX_TOKENS_FOR_ADVANC_MSG_TYPES = 4096

MERGE_ALL_MESSAGES_IN_ONE = False
REDUCE_XML_SIZE = False

ENABLE_SESSION_RECORDINGS = False
SESSION_RECORDINGS_DIR = "logging"
